# Generated by Django 4.1.13 on 2024-01-27 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('owners', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('receipt', models.ImageField(blank=True, upload_to='uploads/receipts/%Y/%m/%d/')),
                ('guarantee', models.ImageField(blank=True, upload_to='uploads/guarantees/%Y/%m/%d/')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('beneficiary', models.CharField(max_length=200)),
                ('benefactor', models.CharField(max_length=200)),
                ('transactions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountant.account')),
            ],
        ),
    ]
