# Generated by Django 4.1.13 on 2024-01-04 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transactions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
