# Generated by Django 4.2.7 on 2024-01-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='guarantee',
            field=models.ImageField(blank=True, upload_to='uploads/guarantees/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.ImageField(blank=True, upload_to='uploads/receipts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='transactions',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accountant.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
