# Generated by Django 4.2.7 on 2024-01-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_transaction_guarantee_transaction_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountant.transaction'),
        ),
    ]
