# Generated by Django 4.1.13 on 2024-02-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_remove_account_viewers_vault_tag_alter_account_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='vault_account', to='accountant.account'),
        ),
    ]
