# Generated by Django 4.1.13 on 2024-01-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_alter_account_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transactions',
            new_name='account',
        ),
    ]
