# Generated by Django 4.1.13 on 2024-02-08 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('accountant', '0003_vault_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('token_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_token', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('authtoken.token',),
        ),
    ]
