# Generated by Django 4.1.13 on 2024-01-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0003_rename_transactions_transaction_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_edited',
        ),
        migrations.AddField(
            model_name='account',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
